version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app/data/chromadb:/app/data/chromadb
      - ./static:/app/static  
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434

  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"
    volumes:
      - /ollama/models/blobs:/ollama/models/blobs
      - /ollama/models/manifests:/ollama/models/manifests