version: "3.8"

services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app/data/chromadb:/app/data/chromadb
      - ./static:/app/static  
    depends_on:
      - ollama
    environment:
      - OLLAMA_HOST=ollama
      - OLLAMA_PORT=11434

  ollama:
    image: ollama/ollama:latest
    container_name: kuasar-rag-system-ollama-1
    ports:
      - "11434:11434"
