version: '3'
services:
  fastapi:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./app/data/chromadb:/app/data/chromadb  
    depends_on:
      - ollama  
  
  ollama:
    image: ollama/ollama:latest
    ports:
      - "11434:11434"  
